### ISSUE TITLE
store pass should be together in keytool command

### ISSUE THREAD

**Issue by Gordiievskyi** [reportportal/documentation#216]
Hi Guys,

In Section TipsAndTricks/HowToResolveIssuesWithJira  there is a command for import cer keytool -importcert -noprompt -file foo.crt -alias "JIRA CERT" -keystore cacerts -store pass abc123

"store pass" should be print together as "storepass"

Thanks,
Slava

**Comment by DzmitryHumianiuk** [comment]
@Gordiievskyi thank you.
We appreciate contribution, do not hesitate to send us Pull Request.
You can edit file right from github page, and sent change for review.
