### ISSUE TITLE
Invalid static images representation in Safari browser [@Demo]

### ISSUE THREAD

**Issue by medoed36** [reportportal/documentation#246]
Link: http://web.demo.reportportal.io/ui/#default_personal/launches/all?page.page=1&page.size=50

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/2526575/46806120-79016a80-cd6f-11e8-8cd9-3144fb47f604.png">

**Comment by DzmitryHumianiuk** [comment]
@medoed36 which version?
it's totally fine for my Safari **Version 11.1.2 (13605.3.8)**

**Comment by medoed36** [comment]
> @medoed36 which version?
> it's totally fine for my Safari **Version 11.1.2 (13605.3.8)**

Version 12.0 (14606.1.36.1.9)

**Comment by DzmitryHumianiuk** [comment]
not reproducible.
verified under safari 12.0.1
